github:
  description: "Apache XML Graphics Commons"
  homepage: https://xmlgraphics.apache.org/commons/
  labels:
    - xgc
    - apache

notifications:
  commits:      commits@xmlgraphics.apache.org
  issues:       general@xmlgraphics.apache.org
  pullrequests: general@xmlgraphics.apache.org
  jira_options: link label
